### ISSUE TITLE
[ENHANCEMENT] Make the Void playerlist clickable

### ISSUE THREAD

**Issue by Grobitalks** [Azurilex/void-issues#12]
Make the names in the void playerlist clickable (select user)

**Comment by Azurilex** [comment]
Void's player list is **optimized**. Each line inside of it is actually a part of the same text object, I just use line breaks so I don't have to continuously update dozens of different text objects.

**Comment by Azurilex** [comment]
I'm open to suggestions on this.

**Comment by Azurilex** [comment]
Please use the format provided when creating an issue.
