### ISSUE TITLE
[ENHANCEMENT]

### ISSUE THREAD

**Issue by NIneFox7097** [Azurilex/void-issues#15]
Legit what I said previously in the server

A target crash, but not the common way most clients do it, have a built in crasher with a gun/laser coming out of your face, point that at a user, and boom gone, make it as inconspicuous as possible, so no sound, avatar isn’t suspicious, but as soon as you toggle the laser, all hell breaks loose

**Comment by C0smicMadeThisForVoidGithubLol** [comment]
I'll make the avatar for this if Azurilex like actually wants to implement it unless he'd rather have someone else ^ But I +1 this aswell, cool idea
