### ISSUE TITLE
[ENHANCEMENT] Target crash

### ISSUE THREAD

**Issue by The-Fuz** [Azurilex/void-issues#17]
Target crash would be a great addition in case you just want to crash a single guy and not bring the entire lobby down with them.

**Comment by C0smicMadeThisForVoidGithubLol** [comment]
Im fairly sure this is something that has been denied multiple times due to being too risky.

**Comment by The-Fuz** [comment]
> I'm fairly sure this is something that has been denied multiple times due to being too risky.

just anything to target crash, does not have to be the block everyone but 1 person thing, an avatar with a laser or something would do, don't see how that is any more risky

**Comment by notunixian** [comment]
mass blocking people can cause trust to lower, meaning you can go from user to new user, etc, etc.
