### ISSUE TITLE
[BUG] Crash when dropping portal to player who blocked you

### ISSUE THREAD

**Issue by SerDubstepCat** [Azurilex/void-issues#20]
**Describe the bug**
Crash happens whenever you click "Drop Portal" under user profile

**To Reproduce**
1. Get blocked
2. Attempt to drop portal to that same user

**Expected behavior**
Probably nothing or portal still dropped to that user if applicable

**Screenshots**
https://user-images.githubusercontent.com/48300512/154815530-472ee664-5e3f-40ca-bcc2-fd5cc90de6d5.mp4

**Additional context**
(This does not happen if you block the user and attempt to drop a portal to them)

**Comment by Azurilex** [comment]
This is fixed in Build 45.
