### ISSUE TITLE
[ENHANCEMENT] on crash popup telling you where void.log is

### ISSUE THREAD

**Issue by The-Fuz** [Azurilex/void-issues#24]
**Describe the feature/suggestion you'd like**
If vrc crashes, a popup that tells you where void.log is and to send it to the discord

**Additional context**
seems like an easy fix to the endless stream of people sending the wrong log or not knowing where it is

**Comment by Azurilex** [comment]
It's pretty impossible to detect crashes reliably without running a separate process to do so.
