### ISSUE TITLE
[ENHANCEMENT] spot on nameplate/playerlist menu for avatar status

### ISSUE THREAD

**Issue by sinlmfao** [Azurilex/void-issues#25]
**Describe the feature/suggestion you'd like**
a type of text depending on their avatar if it is private or public, on their nameplate, or playerlist menu etc

example - PR [PRIVATE]
                 PU [PUBLIC]

**Comment by Azurilex** [comment]
I'll add this to build 51.

**Comment by Azurilex** [comment]
This is ready to go for build 51.
![](https://i.invalid.gg/VRChat_2XhQo7mrmX.png)
