### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by brushxman** [Azurilex/void-issues#27]
**Describe the bug**

**Expected behavior**
A clear and concise description of what you expected to happen
When I fly some avatars always have this like if i fly it has it were it looks like its falling down or something
**Screenshots**

![20220305130203_1](https://user-images.githubusercontent.com/101021429/156899843-d2d81783-5d23-4e96-9d98-1d8493df696e.jpg)

**Comment by Azurilex** [comment]
This is because of a jumping animation your avatar has. This is just a side effect of flight, not a bug.
