### ISSUE TITLE
FPS/PING SPOOFER CRASHING GAME WHEN CLICKED ON

### ISSUE THREAD

**Issue by peebo29** [Azurilex/void-issues#33]
**FPS/PING SPOOFER CRASHING GAME WHEN CLICKED ON**
When u go to misc and change the number of frames that is spoofed

**To Reproduce**
1. opened void menu
2. went to misc
3. game suicides after selecting the amount of spoofed frames 

**Expected behavior**
death basically

**Screenshots**
https://streamable.com/j3ex59 (Video)
https://streamable.com/orqjpw (Video w/ all my mods on cuz 1 was missing)

**Additional context**
nothing else

**Comment by peebo29** [comment]
including the new update :skull:

**Comment by Azurilex** [comment]
Lol, videos were comedic. I'll debug this soon.

**Comment by Azurilex** [comment]
I pushed an update to fix this. I had to backport ImGUI versions because there seems to be a bug with the latest version. Should be all good now 👌
