### ISSUE TITLE
[ENHANCEMENT] Third Person keybind

### ISSUE THREAD

**Issue by peebo29** [Azurilex/void-issues#35]
**Describe the feature/suggestion you'd like**
This is so u could see what's behind or in front of you (most clients probably have this already like munchen, notorious, SVH, etc)
https://streamable.com/xucso5 (Example / WARNING: bear on 2 legs O_o)

**Additional context**
my ass flappable WTF!!!!!!!!

**Comment by Azurilex** [comment]
this is ready in build 59.

**Comment by peebo29** [comment]
awesome
