### ISSUE TITLE
[BUG] E1 Distortion

### ISSUE THREAD

**Issue by GunSlingerEAC** [Azurilex/void-issues#39]
**Describe the bug**
E1 Distortion turns on for 5 seconds then shuts off but is still enabled

**To Reproduce**
1. Turn on E1 distortion
2. wait 5 seconds
3. done its not working anymore after 5 seconds

**Expected behavior**
Kill the questies

**Comment by The-Fuz** [comment]
e1 is not a crasher and should not kill anyone, maybe break audio

**Comment by GunSlingerEAC** [comment]
E1 Crashes Quest users

**Comment by GunSlingerEAC** [comment]
Did it with 3 people and they died

**Comment by Azurilex** [comment]
e1 is purely audio. it is impossible to cause a crash using void's e1 payload.
