### ISSUE TITLE
[ENHANCEMENT] self serve version rollback

### ISSUE THREAD

**Issue by LudoDash** [Azurilex/void-issues#40]
**Describe the feature/suggestion you'd like**
Adding Version rollback option in void loader to download the previous version of void.

**Additional context**
something similar to this
![Capture(1)](https://user-images.githubusercontent.com/18017425/162764719-8e2f564e-99ee-4411-9b65-f5ca65257319.png)

Allow people to go back to a previous version if the new update is not functional.

If a user updates to the latest version but the update breaks their game, or there is a known bug. allowing the user to go back one version will allow the devs more time to fix a bug while a user is still able to use the software even though it may be outdated.
overall, reducing stress for the devs & increasing the stability of the software and the user's experience

**Comment by Azurilex** [comment]
Not implementing this due to possible security issues that could come with this.
