### ISSUE TITLE
[BUG] Game Crashing when attempting to turn VR Playerlist on.

### ISSUE THREAD

**Issue by C0smicMadeThisForVoidGithubLol** [Azurilex/void-issues#7]
**Describe the bug**
The game crashes whenever you're using vrtool and VOID together, and attempt to turn on the playerlist.

**To Reproduce**
1. Inject VRTool and VOID Client
2. Attempt to enable VOID's playerlist.
3. Kablam

**Expected behavior**
I expected my playerlist to come up and not kill me

**Screenshots**
Playerlist Off: https://media.discordapp.net/attachments/926645527251144705/941106534874771496/unknown.png?width=1337&height=702

PlayerList on (can tell its frozen by the two different mouse positions): https://media.discordapp.net/attachments/926645527251144705/941106666064199750/unknown.png?width=1440&height=518

**Additional context**
This requires VRTool and VOID to recreate, so this likely isnt high priority and may not be solveable on Azurilex's end.

**Comment by Azurilex** [comment]
Please upload your void.log file after this crash occurs.

**Comment by C0smicMadeThisForVoidGithubLol** [comment]
No response in Void's log, will still upload the log though
[void.log](https://github.com/Azurilex/void-issues/files/8036780/void.log)
.

**Comment by Azurilex** [comment]
> 

VRT is the one crashing you then. I'm not sure if there's anything I can do on my end to prevent this crash as Void has pretty good exception handling for issues such as these.

**Comment by C0smicMadeThisForVoidGithubLol** [comment]
Hmm. That's sad considering I was using VRTool to keep my "Void Themed Menu" Running and I just assume your debug wont work with Notorious' UI. I'll have to find a work around I suppose because Miinc seems to be very against other client integration. Thank you for responding

**Comment by Azurilex** [comment]
> Hmm. That's sad considering I was using VRTool to keep my "Void Themed Menu" Running and I just assume your debug wont work with Notorious' UI. I'll have to find a work around I suppose because Miinc seems to be very against other client integration. Thank you for responding

If VRTool is sending you any logs you should drop them here.

**Comment by Azurilex** [comment]
Haven't heard anything from this, closing.
