### ISSUE TITLE
[BUG] Whitelisted avatars do not save to config for me. I'm guessing this applies to blacklisted ones too.

### ISSUE THREAD

**Issue by SouljaVR** [Azurilex/void-issues#8]
**Description:**

When I whitelist avatars manually by ID, or through the player select screen, they become whitelisted for the session but after a restart they need to be re-whitelisted. I am saving the config after whitelisting stuff, and I'm saving it to the default config. I also try to manually load the config, but it doesn't change anything.

I'm guessing this also applies to blacklisted avatars though I haven't tested it. All other client settings save fine, it's just the avatar IDs for the whitelist that don't.

**Steps to reproduce the behavior:**

I am running official ML 0.5.2 with 404's freeloading plugin and AMD FSR. I have the VOID appdata folder/loader excluded from my antivirus. This behaviour is persistent even with no other clients or mods for me.

**Expected behavior:**

Any saved blacklisted/whitelisted avatars should be persistent after a game restart and reload of the config. I shouldn't have to re-add ID's after every restart of the gamegame

**Screenshots:**

N/A

**Additional context:**

N/A

**Comment by Azurilex** [comment]
Attempting to reproduce.

**Comment by SouljaVR** [comment]
Did you manage to reproduce this behaviour?

**Comment by Azurilex** [comment]
> Did you manage to reproduce this behaviour?

Yes, I've identified the issue and am working on a fix.

**Comment by Azurilex** [comment]
This is fixed in build 42.
